#!/usr/bin/env python

import sys, os, getopt, subprocess
import antlr3
import readelfLexer
import readelfParser

def main(argv):
    
    # open readelf
    subp = subprocess.Popen(["readelf", "--debug-dump=info", "test-object"], \
                        stdout=subprocess.PIPE, stdin=subprocess.PIPE)
    inputStream = antlr3.ANTLRInputStream(subp.stdout)
    lexer = readelfLexer.readelfLexer(inputStream)
    tokenStream = antlr3.CommonTokenStream(lexer)
    parser = readelfParser.readelfParser(tokenStream)

    # code to do stuff goes here
    print parser.toplevel().tree

def usage():
    name = os.path.basename(sys.argv[0])
    print "Usage:\n"
    print name + "\t [ -o | --outfile output-file ] input-file"
    print name + "\t   -h | --help"
    print name + "\t   -v | --version"


if __name__ == "__main__":
    main(sys.argv[1:])
